server:
  port: 8082  # Identity is 8081, so this sits next door

spring:
  application:
    name: outing-service
  datasource:
    url: jdbc:mysql://localhost:3306/outing_db?createDatabaseIfNotExist=true
    username: root
    password: shreydave2006  # <--- CHANGE THIS
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/